# Font
font:
  size:           18
  
  normal:
    family:         'FantasqueSansMono Nerd Font'
    style:          Regular
  
  bold:
    family:         'FantasqueSansMono Nerd Font'
    style:           Bold
    
    offset:
      x:              0
      y:              0

    glyph_offset:
      x: 0.0
      y: 0.0

    spacing:
      line: 0.0
      letter: 0.0


window:
  padding:
    x:              16
    y:              16
  dynamic_padding:  true


colors:
  primary:
    background:     '#292828'
    foreground:     '#d8be93'
    dim_foreground: '#a5abb6'
 
cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: 'Beam'
 
  vi_mode_cursor:
    text:           '#2e3440'
    cursor:         '#d8dee9'
 
  selection:
    text:           CellBackground
    background:     CellForeground
 
  normal:
     black:         '#1D344F'
     red:           '#C98093'
     green:         '#7ca198'
     yellow:        '#E4B371'
     blue:          '#6080b0'
     magenta:       '#8e6f98'
     cyan:          '#6ca8cf'
     white:         '#CDD1D5'
 
  bright:
     black:         '#1D344F'
     red:           '#C98093'
     green:         '#7ca198'
     yellow:        '#E4B371'
     blue:          '#6080b0'
     magenta:       '#8e6f98'
     cyan:          '#6ca8cf'
     white:         '#CDD1D5'
 
  dim:
     black:         '#1D344F'
     red:           '#C98093'
     green:         '#7ca198'
     yellow:        '#E4B371'
     blue:          '#6080b0'
     magenta:       '#8e6f98'
     cyan:          '#6ca8cf'
     white:         '#CDD1D5'
